version: '3'

volumes:
    gatling_results: {}
    parsed_results: {}

services:
  gatling:
    build: .
    volumes:
      - gatling_results:/opt/gatling/results
    environment: 
      - JAVA_OPTS=${JAVA_OPTS}

  parser: 
    build: 
      context: .
      dockerfile: ./Gatling-Parsing/Dockerfile
    volumes: 
      - gatling_results:/data/results
      - parsed_results:/data/report
    environment:
      - ELASTIC_URL=${ELASTIC_URL} 
      - ELASTIC_ACTIVATE=${ELASTIC_ACTIVATE} 
