version: '3.2'

volumes:
    grafana_data: {}
    prometheus_data: {}

services:

  prometheus:
    build:
      context: ./prometheus/
      args:
        METRICS_USERNAME: ${METRICS_USERNAME?METRICS_USERNAME}
        METRICS_PASSWORD: ${METRICS_PASSWORD?METRICS_PASSWORD}
    depends_on:
      - traefik
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  traefik:
    build:
      context: ./traefik
      args:
        TARGET_SITE: ${TARGET_SITE?TARGET_SITE}
    image: traefik
    ports:
      - 10000:10000
