global:
  checkNewVersion: true
  sendAnonymousUsage: true
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: ":10000"
    proxyProtocol:
      insecure: true
    forwardedHeaders:
      insecure: true
providers:
  file:
    filename: "/etc/traefik/dynamic_config.yml"
    watch: true
log:
  level: "ERROR"
accessLog: {}
#  format: json
#  fields:
#    defaultMode: keep
#    headers:
#      defaultMode: keep
# metrics:
#   prometheus:
#     entryPoint: metrics
#     addEntryPointsLabels: true
#     addServicesLabels: true
# api:
#   dashboard: true